// ----------------------------------------------------------------------
// Copyright 2025 Jody Hagins
// Distributed under the MIT Software License
// See accompanying file LICENSE or copy at
// https://opensource.org/licenses/MIT
// ----------------------------------------------------------------------
#ifndef WJH_ATLAS_F9A7E8B3C4D1E5A6F2B9C8D7E1F4A3B2
#define WJH_ATLAS_F9A7E8B3C4D1E5A6F2B9C8D7E1F4A3B2

#include "atlas/generation/core/ITemplate.hpp"

namespace wjh::atlas::generation { inline namespace v1 {

/**
 * Named constant declarations template
 *
 * Generates named constant declarations inside the class body:
 * - Static const member declarations
 * - Uses 'static const' (not constexpr) because type is incomplete at this
 * point
 * - Each constant is declared as: static const ClassName name;
 *
 * Note: Declarations appear inside the class body. The corresponding
 * definitions are generated by ConstantDefinitionsTemplate outside the class.
 */
class ConstantDeclarationsTemplate final
: public ITemplate
{
protected:
    [[nodiscard]]
    std::string id_impl() const override
    {
        return "features.constant_declarations";
    }

    [[nodiscard]]
    std::string_view get_template_impl() const noexcept override;

    [[nodiscard]]
    bool should_apply_impl(ClassInfo const & info) const override;

    [[nodiscard]]
    boost::json::object prepare_variables_impl(
        ClassInfo const & info) const override;
};

/**
 * Named constant definitions template
 *
 * Generates named constant definitions outside the class body:
 * - Inline static constants initialized with specific values
 * - Uses 'inline constexpr' to make them usable in constexpr contexts
 * - Each constant is defined as: inline constexpr Type Type::name =
 * Type(value);
 *
 * Note: Definitions appear after the class body closes. The corresponding
 * declarations are generated by ConstantDeclarationsTemplate inside the class.
 */
class ConstantDefinitionsTemplate final
: public ITemplate
{
protected:
    [[nodiscard]]
    std::string id_impl() const override
    {
        return "features.constant_definitions";
    }

    [[nodiscard]]
    std::string_view get_template_impl() const noexcept override;

    [[nodiscard]]
    bool should_apply_impl(ClassInfo const & info) const override;

    [[nodiscard]]
    boost::json::object prepare_variables_impl(
        ClassInfo const & info) const override;
};

}} // namespace wjh::atlas::generation::v1

#endif // WJH_ATLAS_F9A7E8B3C4D1E5A6F2B9C8D7E1F4A3B2
